/*
  data.js - contains vocabulary and sentence seeds.
*/

(function (global) {
  const HB = (global.HB = global.HB || {});

const vocabList = [
  { hanzi: '你', pinyin: 'ni', meaning: 'bạn' },
  { hanzi: '好', pinyin: 'hao', meaning: 'tốt' },
  { hanzi: '我', pinyin: 'wo', meaning: 'tôi' },
  { hanzi: '不', pinyin: 'bu', meaning: 'không' },
  { hanzi: '五', pinyin: 'wu', meaning: 'năm' },
  { hanzi: '他', pinyin: 'ta', meaning: 'anh ấy' },
  { hanzi: '她', pinyin: 'ta', meaning: 'cô ấy' },
  { hanzi: '大', pinyin: 'da', meaning: 'to' },
  { hanzi: '口', pinyin: 'kou', meaning: 'miệng' },
  { hanzi: '白', pinyin: 'bai', meaning: 'trắng' },
  { hanzi: '吗', pinyin: 'ma', meaning: 'trợ từ nghi vấn' },
  { hanzi: '马', pinyin: 'ma', meaning: 'ngựa' },
  { hanzi: '妈', pinyin: 'ma', meaning: 'mẹ' },
  { hanzi: '八', pinyin: 'ba', meaning: 'tám' },
  { hanzi: '很', pinyin: 'hen', meaning: 'rất' },
  { hanzi: '忙', pinyin: 'mang', meaning: 'bận' },
  { hanzi: '难', pinyin: 'nan', meaning: 'khó' },
  { hanzi: '语', pinyin: 'yu', meaning: 'ngôn ngữ' },
  { hanzi: '汉', pinyin: 'han', meaning: 'Hán' },
  { hanzi: '人', pinyin: 'ren', meaning: 'người' },
  { hanzi: '爸', pinyin: 'ba', meaning: 'bố' },
  { hanzi: '太', pinyin: 'tai', meaning: 'quá' },
  { hanzi: '弟', pinyin: 'di', meaning: 'em trai' },
  { hanzi: '男', pinyin: 'nan', meaning: 'nam' },
  { hanzi: '哥', pinyin: 'ge', meaning: 'anh trai' },
  { hanzi: '妹', pinyin: 'mei', meaning: 'em gái' },
  { hanzi: '学', pinyin: 'xue', meaning: 'học' },
  { hanzi: '英', pinyin: 'ying', meaning: 'Anh (nước Anh)' },
  { hanzi: '得', pinyin: 'de', meaning: 'rất/được' },
  { hanzi: '饿', pinyin: 'e', meaning: 'đói' },
  { hanzi: '去', pinyin: 'qu', meaning: 'đi' },
  { hanzi: '法', pinyin: 'fa', meaning: 'Pháp' },
  { hanzi: '韩', pinyin: 'han', meaning: 'Hàn Quốc' },
  { hanzi: '国', pinyin: 'guo', meaning: 'quốc gia' },
  { hanzi: '日', pinyin: 'ri', meaning: 'Nhật' },
  { hanzi: '对', pinyin: 'dui', meaning: 'đúng' },
  { hanzi: '也', pinyin: 'ye', meaning: 'cũng' },
  { hanzi: '天', pinyin: 'tian', meaning: 'ngày trời' },
  { hanzi: '明', pinyin: 'ming', meaning: 'sáng/mai' },
  { hanzi: '见', pinyin: 'jian', meaning: 'gặp' },
  { hanzi: '邮局', pinyin: 'you ju', meaning: 'bưu điện' },
  { hanzi: '寄', pinyin: 'ji', meaning: 'gửi' },
  { hanzi: '信', pinyin: 'xin', meaning: 'thư' },
];

const easySentences = [
  { hanzi: '你好吗？', pinyin: 'ni hao ma', meaning: 'Bạn khỏe không?' },
  { hanzi: '我很好。', pinyin: 'wo hen hao', meaning: 'Tôi rất khỏe.' },
  { hanzi: '你忙吗？', pinyin: 'ni mang ma', meaning: 'Bạn bận không?' },
  { hanzi: '我不忙。', pinyin: 'wo bu mang', meaning: 'Tôi không bận.' },
  { hanzi: '他是中国人。', pinyin: 'ta shi zhong guo ren', meaning: 'Anh ấy là người Trung Quốc.' },
  { hanzi: '她是老师。', pinyin: 'ta shi lao shi', meaning: 'Cô ấy là giáo viên.' },
  { hanzi: '我们学汉语。', pinyin: 'wo men xue han yu', meaning: 'Chúng tôi học tiếng Hán.' },
  { hanzi: '你呢？', pinyin: 'ni ne', meaning: 'Còn bạn?' },
  { hanzi: '他也学英语。', pinyin: 'ta ye xue ying yu', meaning: 'Anh ấy cũng học tiếng Anh.' },
  { hanzi: '我去邮局寄信。', pinyin: 'wo qu you ju ji xin', meaning: 'Tôi đi bưu điện gửi thư.' },
  { hanzi: '我很忙。', pinyin: 'wo hen mang', meaning: 'Tôi rất bận.' },
  { hanzi: '我忙吗？', pinyin: 'wo mang ma', meaning: 'Tôi bận phải không?' },
  { hanzi: '我很饿。', pinyin: 'wo hen e', meaning: 'Tôi rất đói.' },
  { hanzi: '我不饿。', pinyin: 'wo bu e', meaning: 'Tôi không đói.' },
  { hanzi: '我饿吗？', pinyin: 'wo e ma', meaning: 'Tôi đói phải không?' },
  { hanzi: '我很白。', pinyin: 'wo hen bai', meaning: 'Tôi rất trắng.' },
  { hanzi: '我不白。', pinyin: 'wo bu bai', meaning: 'Tôi không trắng.' },
  { hanzi: '我白吗？', pinyin: 'wo bai ma', meaning: 'Tôi trắng phải không?' },
  { hanzi: '我很大。', pinyin: 'wo hen da', meaning: 'Tôi rất to.' },
  { hanzi: '我不大。', pinyin: 'wo bu da', meaning: 'Tôi không to.' },
  { hanzi: '我大吗？', pinyin: 'wo da ma', meaning: 'Tôi to phải không?' },
  { hanzi: '你很忙。', pinyin: 'ni hen mang', meaning: 'Bạn rất bận.' },
  { hanzi: '你不忙。', pinyin: 'ni bu mang', meaning: 'Bạn không bận.' },
  { hanzi: '你很饿。', pinyin: 'ni hen e', meaning: 'Bạn rất đói.' },
  { hanzi: '你不饿。', pinyin: 'ni bu e', meaning: 'Bạn không đói.' },
  { hanzi: '你饿吗？', pinyin: 'ni e ma', meaning: 'Bạn đói phải không?' },
  { hanzi: '你很白。', pinyin: 'ni hen bai', meaning: 'Bạn rất trắng.' },
  { hanzi: '你不白。', pinyin: 'ni bu bai', meaning: 'Bạn không trắng.' },
  { hanzi: '你白吗？', pinyin: 'ni bai ma', meaning: 'Bạn trắng phải không?' },
  { hanzi: '你很大。', pinyin: 'ni hen da', meaning: 'Bạn rất to.' },
  { hanzi: '你不大。', pinyin: 'ni bu da', meaning: 'Bạn không to.' },
  { hanzi: '你大吗？', pinyin: 'ni da ma', meaning: 'Bạn to phải không?' },
  { hanzi: '他很忙。', pinyin: 'ta hen mang', meaning: 'Anh ấy rất bận.' },
  { hanzi: '他不忙。', pinyin: 'ta bu mang', meaning: 'Anh ấy không bận.' },
  { hanzi: '他忙吗？', pinyin: 'ta mang ma', meaning: 'Anh ấy bận phải không?' },
  { hanzi: '他很饿。', pinyin: 'ta hen e', meaning: 'Anh ấy rất đói.' },
  { hanzi: '他不饿。', pinyin: 'ta bu e', meaning: 'Anh ấy không đói.' },
  { hanzi: '他饿吗？', pinyin: 'ta e ma', meaning: 'Anh ấy đói phải không?' },
  { hanzi: '他很白。', pinyin: 'ta hen bai', meaning: 'Anh ấy rất trắng.' },
  { hanzi: '他不白。', pinyin: 'ta bu bai', meaning: 'Anh ấy không trắng.' },
  { hanzi: '他白吗？', pinyin: 'ta bai ma', meaning: 'Anh ấy trắng phải không?' },
  { hanzi: '他很大。', pinyin: 'ta hen da', meaning: 'Anh ấy rất to.' },
  { hanzi: '他不大。', pinyin: 'ta bu da', meaning: 'Anh ấy không to.' },
  { hanzi: '他大吗？', pinyin: 'ta da ma', meaning: 'Anh ấy to phải không?' },
  { hanzi: '她很忙。', pinyin: 'ta hen mang', meaning: 'Cô ấy rất bận.' },
  { hanzi: '她不忙。', pinyin: 'ta bu mang', meaning: 'Cô ấy không bận.' },
  { hanzi: '她忙吗？', pinyin: 'ta mang ma', meaning: 'Cô ấy bận phải không?' },
  { hanzi: '她很饿。', pinyin: 'ta hen e', meaning: 'Cô ấy rất đói.' },
  { hanzi: '她不饿。', pinyin: 'ta bu e', meaning: 'Cô ấy không đói.' },
  { hanzi: '她饿吗？', pinyin: 'ta e ma', meaning: 'Cô ấy đói phải không?' },
  { hanzi: '她很白。', pinyin: 'ta hen bai', meaning: 'Cô ấy rất trắng.' },
  { hanzi: '她不白。', pinyin: 'ta bu bai', meaning: 'Cô ấy không trắng.' },
  { hanzi: '她白吗？', pinyin: 'ta bai ma', meaning: 'Cô ấy trắng phải không?' },
  { hanzi: '她很大。', pinyin: 'ta hen da', meaning: 'Cô ấy rất to.' },
  { hanzi: '她不大。', pinyin: 'ta bu da', meaning: 'Cô ấy không to.' },
  { hanzi: '她大吗？', pinyin: 'ta da ma', meaning: 'Cô ấy to phải không?' },
  { hanzi: '爸爸很忙。', pinyin: 'ba ba hen mang', meaning: 'Bố rất bận.' },
  { hanzi: '爸爸不忙。', pinyin: 'ba ba bu mang', meaning: 'Bố không bận.' },
  { hanzi: '爸爸忙吗？', pinyin: 'ba ba mang ma', meaning: 'Bố bận phải không?' },
  { hanzi: '爸爸很饿。', pinyin: 'ba ba hen e', meaning: 'Bố rất đói.' },
  { hanzi: '爸爸不饿。', pinyin: 'ba ba bu e', meaning: 'Bố không đói.' },
  { hanzi: '爸爸饿吗？', pinyin: 'ba ba e ma', meaning: 'Bố đói phải không?' },
  { hanzi: '爸爸很白。', pinyin: 'ba ba hen bai', meaning: 'Bố rất trắng.' },
  { hanzi: '爸爸不白。', pinyin: 'ba ba bu bai', meaning: 'Bố không trắng.' },
  { hanzi: '爸爸白吗？', pinyin: 'ba ba bai ma', meaning: 'Bố trắng phải không?' },
  { hanzi: '爸爸很大。', pinyin: 'ba ba hen da', meaning: 'Bố rất to.' },
  { hanzi: '爸爸不大。', pinyin: 'ba ba bu da', meaning: 'Bố không to.' },
  { hanzi: '爸爸大吗？', pinyin: 'ba ba da ma', meaning: 'Bố to phải không?' },
  { hanzi: '妈妈很忙。', pinyin: 'ma ma hen mang', meaning: 'Mẹ rất bận.' },
  { hanzi: '妈妈不忙。', pinyin: 'ma ma bu mang', meaning: 'Mẹ không bận.' },
  { hanzi: '妈妈忙吗？', pinyin: 'ma ma mang ma', meaning: 'Mẹ bận phải không?' },
  { hanzi: '妈妈很饿。', pinyin: 'ma ma hen e', meaning: 'Mẹ rất đói.' },
  { hanzi: '妈妈不饿。', pinyin: 'ma ma bu e', meaning: 'Mẹ không đói.' },
  { hanzi: '妈妈饿吗？', pinyin: 'ma ma e ma', meaning: 'Mẹ đói phải không?' },
  { hanzi: '妈妈很白。', pinyin: 'ma ma hen bai', meaning: 'Mẹ rất trắng.' },
  { hanzi: '妈妈不白。', pinyin: 'ma ma bu bai', meaning: 'Mẹ không trắng.' },
  { hanzi: '妈妈白吗？', pinyin: 'ma ma bai ma', meaning: 'Mẹ trắng phải không?' },
  { hanzi: '妈妈很大。', pinyin: 'ma ma hen da', meaning: 'Mẹ rất to.' },
  { hanzi: '妈妈不大。', pinyin: 'ma ma bu da', meaning: 'Mẹ không to.' },
  { hanzi: '妈妈大吗？', pinyin: 'ma ma da ma', meaning: 'Mẹ to phải không?' },
  { hanzi: '哥哥很忙。', pinyin: 'ge ge hen mang', meaning: 'Anh trai rất bận.' },
  { hanzi: '哥哥不忙。', pinyin: 'ge ge bu mang', meaning: 'Anh trai không bận.' },
  { hanzi: '哥哥忙吗？', pinyin: 'ge ge mang ma', meaning: 'Anh trai bận phải không?' },
  { hanzi: '哥哥很饿。', pinyin: 'ge ge hen e', meaning: 'Anh trai rất đói.' },
  { hanzi: '哥哥不饿。', pinyin: 'ge ge bu e', meaning: 'Anh trai không đói.' },
  { hanzi: '哥哥饿吗？', pinyin: 'ge ge e ma', meaning: 'Anh trai đói phải không?' },
  { hanzi: '哥哥很白。', pinyin: 'ge ge hen bai', meaning: 'Anh trai rất trắng.' },
  { hanzi: '哥哥不白。', pinyin: 'ge ge bu bai', meaning: 'Anh trai không trắng.' },
  { hanzi: '哥哥白吗？', pinyin: 'ge ge bai ma', meaning: 'Anh trai trắng phải không?' },
  { hanzi: '哥哥很大。', pinyin: 'ge ge hen da', meaning: 'Anh trai rất to.' },
  { hanzi: '哥哥不大。', pinyin: 'ge ge bu da', meaning: 'Anh trai không to.' },
  { hanzi: '哥哥大吗？', pinyin: 'ge ge da ma', meaning: 'Anh trai to phải không?' },
  { hanzi: '弟弟很忙。', pinyin: 'di di hen mang', meaning: 'Em trai rất bận.' },
  { hanzi: '弟弟不忙。', pinyin: 'di di bu mang', meaning: 'Em trai không bận.' },
  { hanzi: '弟弟忙吗？', pinyin: 'di di mang ma', meaning: 'Em trai bận phải không?' },
  { hanzi: '弟弟很饿。', pinyin: 'di di hen e', meaning: 'Em trai rất đói.' },
  { hanzi: '弟弟不饿。', pinyin: 'di di bu e', meaning: 'Em trai không đói.' },
  { hanzi: '弟弟饿吗？', pinyin: 'di di e ma', meaning: 'Em trai đói phải không?' },
  { hanzi: '弟弟很白。', pinyin: 'di di hen bai', meaning: 'Em trai rất trắng.' },
  { hanzi: '弟弟不白。', pinyin: 'di di bu bai', meaning: 'Em trai không trắng.' },
  { hanzi: '弟弟白吗？', pinyin: 'di di bai ma', meaning: 'Em trai trắng phải không?' },
  { hanzi: '弟弟很大。', pinyin: 'di di hen da', meaning: 'Em trai rất to.' },
  { hanzi: '弟弟不大。', pinyin: 'di di bu da', meaning: 'Em trai không to.' },
  { hanzi: '弟弟大吗？', pinyin: 'di di da ma', meaning: 'Em trai to phải không?' },
  { hanzi: '妹妹很忙。', pinyin: 'mei mei hen mang', meaning: 'Em gái rất bận.' },
  { hanzi: '妹妹不忙。', pinyin: 'mei mei bu mang', meaning: 'Em gái không bận.' },
  { hanzi: '妹妹忙吗？', pinyin: 'mei mei mang ma', meaning: 'Em gái bận phải không?' },
  { hanzi: '妹妹很饿。', pinyin: 'mei mei hen e', meaning: 'Em gái rất đói.' },
  { hanzi: '妹妹不饿。', pinyin: 'mei mei bu e', meaning: 'Em gái không đói.' },
  { hanzi: '妹妹饿吗？', pinyin: 'mei mei e ma', meaning: 'Em gái đói phải không?' },
  { hanzi: '妹妹很白。', pinyin: 'mei mei hen bai', meaning: 'Em gái rất trắng.' },
  { hanzi: '妹妹不白。', pinyin: 'mei mei bu bai', meaning: 'Em gái không trắng.' },
  { hanzi: '妹妹白吗？', pinyin: 'mei mei bai ma', meaning: 'Em gái trắng phải không?' },
  { hanzi: '妹妹很大。', pinyin: 'mei mei hen da', meaning: 'Em gái rất to.' },
  { hanzi: '妹妹不大。', pinyin: 'mei mei bu da', meaning: 'Em gái không to.' },
  { hanzi: '妹妹大吗？', pinyin: 'mei mei da ma', meaning: 'Em gái to phải không?' },
  { hanzi: '你去邮局寄信。', pinyin: 'ni qu you ju ji xin', meaning: 'Bạn đi bưu điện gửi thư.' },
  { hanzi: '他去邮局寄信。', pinyin: 'ta qu you ju ji xin', meaning: 'Anh ấy đi bưu điện gửi thư.' },
  { hanzi: '她去邮局寄信。', pinyin: 'ta qu you ju ji xin', meaning: 'Cô ấy đi bưu điện gửi thư.' },
  { hanzi: '爸爸去邮局寄信。', pinyin: 'ba ba qu you ju ji xin', meaning: 'Bố đi bưu điện gửi thư.' },
  { hanzi: '妈妈去邮局寄信。', pinyin: 'ma ma qu you ju ji xin', meaning: 'Mẹ đi bưu điện gửi thư.' },
  { hanzi: '哥哥去邮局寄信。', pinyin: 'ge ge qu you ju ji xin', meaning: 'Anh trai đi bưu điện gửi thư.' },
  { hanzi: '弟弟去邮局寄信。', pinyin: 'di di qu you ju ji xin', meaning: 'Em trai đi bưu điện gửi thư.' },
  { hanzi: '妹妹去邮局寄信。', pinyin: 'mei mei qu you ju ji xin', meaning: 'Em gái đi bưu điện gửi thư.' },
  { hanzi: '我学汉语。', pinyin: 'wo xue han yu', meaning: 'Tôi học tiếng Hán.' },
  { hanzi: '我学英语。', pinyin: 'wo xue ying yu', meaning: 'Tôi học tiếng Anh.' },
  { hanzi: '你学汉语。', pinyin: 'ni xue han yu', meaning: 'Bạn học tiếng Hán.' },
  { hanzi: '你学英语。', pinyin: 'ni xue ying yu', meaning: 'Bạn học tiếng Anh.' },
  { hanzi: '他学汉语。', pinyin: 'ta xue han yu', meaning: 'Anh ấy học tiếng Hán.' },
  { hanzi: '他学英语。', pinyin: 'ta xue ying yu', meaning: 'Anh ấy học tiếng Anh.' },
  { hanzi: '她学汉语。', pinyin: 'ta xue han yu', meaning: 'Cô ấy học tiếng Hán.' },
  { hanzi: '她学英语。', pinyin: 'ta xue ying yu', meaning: 'Cô ấy học tiếng Anh.' },
  { hanzi: '爸爸学汉语。', pinyin: 'ba ba xue han yu', meaning: 'Bố học tiếng Hán.' },
  { hanzi: '爸爸学英语。', pinyin: 'ba ba xue ying yu', meaning: 'Bố học tiếng Anh.' },
  { hanzi: '妈妈学汉语。', pinyin: 'ma ma xue han yu', meaning: 'Mẹ học tiếng Hán.' },
  { hanzi: '妈妈学英语。', pinyin: 'ma ma xue ying yu', meaning: 'Mẹ học tiếng Anh.' },
  { hanzi: '哥哥学汉语。', pinyin: 'ge ge xue han yu', meaning: 'Anh trai học tiếng Hán.' },
  { hanzi: '哥哥学英语。', pinyin: 'ge ge xue ying yu', meaning: 'Anh trai học tiếng Anh.' },
  { hanzi: '弟弟学汉语。', pinyin: 'di di xue han yu', meaning: 'Em trai học tiếng Hán.' },
  { hanzi: '弟弟学英语。', pinyin: 'di di xue ying yu', meaning: 'Em trai học tiếng Anh.' },
  { hanzi: '妹妹学汉语。', pinyin: 'mei mei xue han yu', meaning: 'Em gái học tiếng Hán.' },
  { hanzi: '妹妹学英语。', pinyin: 'mei mei xue ying yu', meaning: 'Em gái học tiếng Anh.' },
  { hanzi: '我们明天见。', pinyin: 'wo men ming tian jian', meaning: 'Chúng ta gặp nhau ngày mai.' },
  { hanzi: '明天见。', pinyin: 'ming tian jian', meaning: 'Hẹn gặp ngày mai.' }
];

const hardSentences = [
  { hanzi: '你弟弟忙不忙？', pinyin: 'ni di di mang bu mang', meaning: 'Em trai bạn bận không?' },
  { hanzi: '他太忙了。', pinyin: 'ta tai mang le', meaning: 'Nó bận quá.' },
  { hanzi: '你哥哥是哪国人？', pinyin: 'ni ge ge shi na guo ren', meaning: 'Anh trai bạn là người nước nào?' },
  { hanzi: '他是韩国人。', pinyin: 'ta shi han guo ren', meaning: 'Anh ấy là người Hàn Quốc.' },
  { hanzi: '你饿不饿？', pinyin: 'ni e bu e', meaning: 'Bạn đói không?' },
  { hanzi: '不饿。', pinyin: 'wo bu e', meaning: 'Tôi không đói.' },
  { hanzi: '我们明天见。', pinyin: 'wo men ming tian jian', meaning: 'Chúng ta gặp nhau ngày mai.' },
  { hanzi: '你妈妈忙不忙？', pinyin: 'ni ma ma mang bu mang', meaning: 'Mẹ bạn bận không?' },
  { hanzi: '她很忙。', pinyin: 'ta hen mang', meaning: 'Bà ấy rất bận.' },
  { hanzi: '你去邮局做什么？', pinyin: 'ni qu you ju zuo shen me', meaning: 'Bạn đi bưu điện làm gì?' },
  { hanzi: '我去寄信。', pinyin: 'wo qu ji xin', meaning: 'Tôi đi gửi thư.' },
  { hanzi: '我太忙了。', pinyin: 'wo tai mang le', meaning: 'Tôi quá bận.' },
  { hanzi: '我很忙吗？', pinyin: 'wo hen mang ma', meaning: 'Tôi rất bận phải không?' },
  { hanzi: '我太饿了。', pinyin: 'wo tai e le', meaning: 'Tôi quá đói.' },
  { hanzi: '我很饿吗？', pinyin: 'wo hen e ma', meaning: 'Tôi rất đói phải không?' },
  { hanzi: '我太白了。', pinyin: 'wo tai bai le', meaning: 'Tôi quá trắng.' },
  { hanzi: '我很白吗？', pinyin: 'wo hen bai ma', meaning: 'Tôi rất trắng phải không?' },
  { hanzi: '我太大了。', pinyin: 'wo tai da le', meaning: 'Tôi quá to.' },
  { hanzi: '我很大吗？', pinyin: 'wo hen da ma', meaning: 'Tôi rất to phải không?' },
  { hanzi: '你太忙了。', pinyin: 'ni tai mang le', meaning: 'Bạn quá bận.' },
  { hanzi: '你很忙吗？', pinyin: 'ni hen mang ma', meaning: 'Bạn rất bận phải không?' },
  { hanzi: '你太饿了。', pinyin: 'ni tai e le', meaning: 'Bạn quá đói.' },
  { hanzi: '你很饿吗？', pinyin: 'ni hen e ma', meaning: 'Bạn rất đói phải không?' },
  { hanzi: '你太白了。', pinyin: 'ni tai bai le', meaning: 'Bạn quá trắng.' },
  { hanzi: '你很白吗？', pinyin: 'ni hen bai ma', meaning: 'Bạn rất trắng phải không?' },
  { hanzi: '你太大了。', pinyin: 'ni tai da le', meaning: 'Bạn quá to.' },
  { hanzi: '你很大吗？', pinyin: 'ni hen da ma', meaning: 'Bạn rất to phải không?' },
  { hanzi: '他很忙吗？', pinyin: 'ta hen mang ma', meaning: 'Anh ấy rất bận phải không?' },
  { hanzi: '他太饿了。', pinyin: 'ta tai e le', meaning: 'Anh ấy quá đói.' },
  { hanzi: '他很饿吗？', pinyin: 'ta hen e ma', meaning: 'Anh ấy rất đói phải không?' },
  { hanzi: '他太白了。', pinyin: 'ta tai bai le', meaning: 'Anh ấy quá trắng.' },
  { hanzi: '他很白吗？', pinyin: 'ta hen bai ma', meaning: 'Anh ấy rất trắng phải không?' },
  { hanzi: '他太大了。', pinyin: 'ta tai da le', meaning: 'Anh ấy quá to.' },
  { hanzi: '他很大吗？', pinyin: 'ta hen da ma', meaning: 'Anh ấy rất to phải không?' },
  { hanzi: '她太忙了。', pinyin: 'ta tai mang le', meaning: 'Cô ấy quá bận.' },
  { hanzi: '她很忙吗？', pinyin: 'ta hen mang ma', meaning: 'Cô ấy rất bận phải không?' },
  { hanzi: '她太饿了。', pinyin: 'ta tai e le', meaning: 'Cô ấy quá đói.' },
  { hanzi: '她很饿吗？', pinyin: 'ta hen e ma', meaning: 'Cô ấy rất đói phải không?' },
  { hanzi: '她太白了。', pinyin: 'ta tai bai le', meaning: 'Cô ấy quá trắng.' },
  { hanzi: '她很白吗？', pinyin: 'ta hen bai ma', meaning: 'Cô ấy rất trắng phải không?' },
  { hanzi: '她太大了。', pinyin: 'ta tai da le', meaning: 'Cô ấy quá to.' },
  { hanzi: '她很大吗？', pinyin: 'ta hen da ma', meaning: 'Cô ấy rất to phải không?' },
  { hanzi: '爸爸太忙了。', pinyin: 'ba ba tai mang le', meaning: 'Bố quá bận.' },
  { hanzi: '爸爸很忙吗？', pinyin: 'ba ba hen mang ma', meaning: 'Bố rất bận phải không?' },
  { hanzi: '爸爸太饿了。', pinyin: 'ba ba tai e le', meaning: 'Bố quá đói.' },
  { hanzi: '爸爸很饿吗？', pinyin: 'ba ba hen e ma', meaning: 'Bố rất đói phải không?' },
  { hanzi: '爸爸太白了。', pinyin: 'ba ba tai bai le', meaning: 'Bố quá trắng.' },
  { hanzi: '爸爸很白吗？', pinyin: 'ba ba hen bai ma', meaning: 'Bố rất trắng phải không?' },
  { hanzi: '爸爸太大了。', pinyin: 'ba ba tai da le', meaning: 'Bố quá to.' },
  { hanzi: '爸爸很大吗？', pinyin: 'ba ba hen da ma', meaning: 'Bố rất to phải không?' },
  { hanzi: '妈妈太忙了。', pinyin: 'ma ma tai mang le', meaning: 'Mẹ quá bận.' },
  { hanzi: '妈妈很忙吗？', pinyin: 'ma ma hen mang ma', meaning: 'Mẹ rất bận phải không?' },
  { hanzi: '妈妈太饿了。', pinyin: 'ma ma tai e le', meaning: 'Mẹ quá đói.' },
  { hanzi: '妈妈很饿吗？', pinyin: 'ma ma hen e ma', meaning: 'Mẹ rất đói phải không?' },
  { hanzi: '妈妈太白了。', pinyin: 'ma ma tai bai le', meaning: 'Mẹ quá trắng.' },
  { hanzi: '妈妈很白吗？', pinyin: 'ma ma hen bai ma', meaning: 'Mẹ rất trắng phải không?' },
  { hanzi: '妈妈太大了。', pinyin: 'ma ma tai da le', meaning: 'Mẹ quá to.' },
  { hanzi: '妈妈很大吗？', pinyin: 'ma ma hen da ma', meaning: 'Mẹ rất to phải không?' },
  { hanzi: '哥哥太忙了。', pinyin: 'ge ge tai mang le', meaning: 'Anh trai quá bận.' },
  { hanzi: '哥哥很忙吗？', pinyin: 'ge ge hen mang ma', meaning: 'Anh trai rất bận phải không?' },
  { hanzi: '哥哥太饿了。', pinyin: 'ge ge tai e le', meaning: 'Anh trai quá đói.' },
  { hanzi: '哥哥很饿吗？', pinyin: 'ge ge hen e ma', meaning: 'Anh trai rất đói phải không?' },
  { hanzi: '哥哥太白了。', pinyin: 'ge ge tai bai le', meaning: 'Anh trai quá trắng.' },
  { hanzi: '哥哥很白吗？', pinyin: 'ge ge hen bai ma', meaning: 'Anh trai rất trắng phải không?' },
  { hanzi: '哥哥太大了。', pinyin: 'ge ge tai da le', meaning: 'Anh trai quá to.' },
  { hanzi: '哥哥很大吗？', pinyin: 'ge ge hen da ma', meaning: 'Anh trai rất to phải không?' },
  { hanzi: '弟弟太忙了。', pinyin: 'di di tai mang le', meaning: 'Em trai quá bận.' },
  { hanzi: '弟弟很忙吗？', pinyin: 'di di hen mang ma', meaning: 'Em trai rất bận phải không?' },
  { hanzi: '弟弟太饿了。', pinyin: 'di di tai e le', meaning: 'Em trai quá đói.' },
  { hanzi: '弟弟很饿吗？', pinyin: 'di di hen e ma', meaning: 'Em trai rất đói phải không?' },
  { hanzi: '弟弟太白了。', pinyin: 'di di tai bai le', meaning: 'Em trai quá trắng.' },
  { hanzi: '弟弟很白吗？', pinyin: 'di di hen bai ma', meaning: 'Em trai rất trắng phải không?' },
  { hanzi: '弟弟太大了。', pinyin: 'di di tai da le', meaning: 'Em trai quá to.' },
  { hanzi: '弟弟很大吗？', pinyin: 'di di hen da ma', meaning: 'Em trai rất to phải không?' },
  { hanzi: '妹妹太忙了。', pinyin: 'mei mei tai mang le', meaning: 'Em gái quá bận.' },
  { hanzi: '妹妹很忙吗？', pinyin: 'mei mei hen mang ma', meaning: 'Em gái rất bận phải không?' },
  { hanzi: '妹妹太饿了。', pinyin: 'mei mei tai e le', meaning: 'Em gái quá đói.' },
  { hanzi: '妹妹很饿吗？', pinyin: 'mei mei hen e ma', meaning: 'Em gái rất đói phải không?' },
  { hanzi: '妹妹太白了。', pinyin: 'mei mei tai bai le', meaning: 'Em gái quá trắng.' },
  { hanzi: '妹妹很白吗？', pinyin: 'mei mei hen bai ma', meaning: 'Em gái rất trắng phải không?' },
  { hanzi: '妹妹太大了。', pinyin: 'mei mei tai da le', meaning: 'Em gái quá to.' },
  { hanzi: '妹妹很大吗？', pinyin: 'mei mei hen da ma', meaning: 'Em gái rất to phải không?' },
  { hanzi: '我去邮局寄信吗？', pinyin: 'wo qu you ju ji xin ma', meaning: 'Tôi đi bưu điện gửi thư phải không?' },
  { hanzi: '我明天去邮局寄信。', pinyin: 'wo ming tian qu you ju ji xin', meaning: 'Tôi ngày mai đi bưu điện gửi thư.' },
  { hanzi: '我明天去邮局寄信吗？', pinyin: 'wo ming tian qu you ju ji xin ma', meaning: 'Tôi ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '你去邮局寄信吗？', pinyin: 'ni qu you ju ji xin ma', meaning: 'Bạn đi bưu điện gửi thư phải không?' },
  { hanzi: '你明天去邮局寄信。', pinyin: 'ni ming tian qu you ju ji xin', meaning: 'Bạn ngày mai đi bưu điện gửi thư.' },
  { hanzi: '你明天去邮局寄信吗？', pinyin: 'ni ming tian qu you ju ji xin ma', meaning: 'Bạn ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '他去邮局寄信吗？', pinyin: 'ta qu you ju ji xin ma', meaning: 'Anh ấy đi bưu điện gửi thư phải không?' },
  { hanzi: '他明天去邮局寄信。', pinyin: 'ta ming tian qu you ju ji xin', meaning: 'Anh ấy ngày mai đi bưu điện gửi thư.' },
  { hanzi: '他明天去邮局寄信吗？', pinyin: 'ta ming tian qu you ju ji xin ma', meaning: 'Anh ấy ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '她去邮局寄信吗？', pinyin: 'ta qu you ju ji xin ma', meaning: 'Cô ấy đi bưu điện gửi thư phải không?' },
  { hanzi: '她明天去邮局寄信。', pinyin: 'ta ming tian qu you ju ji xin', meaning: 'Cô ấy ngày mai đi bưu điện gửi thư.' },
  { hanzi: '她明天去邮局寄信吗？', pinyin: 'ta ming tian qu you ju ji xin ma', meaning: 'Cô ấy ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '爸爸去邮局寄信吗？', pinyin: 'ba ba qu you ju ji xin ma', meaning: 'Bố đi bưu điện gửi thư phải không?' },
  { hanzi: '爸爸明天去邮局寄信。', pinyin: 'ba ba ming tian qu you ju ji xin', meaning: 'Bố ngày mai đi bưu điện gửi thư.' },
  { hanzi: '爸爸明天去邮局寄信吗？', pinyin: 'ba ba ming tian qu you ju ji xin ma', meaning: 'Bố ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '妈妈去邮局寄信吗？', pinyin: 'ma ma qu you ju ji xin ma', meaning: 'Mẹ đi bưu điện gửi thư phải không?' },
  { hanzi: '妈妈明天去邮局寄信。', pinyin: 'ma ma ming tian qu you ju ji xin', meaning: 'Mẹ ngày mai đi bưu điện gửi thư.' },
  { hanzi: '妈妈明天去邮局寄信吗？', pinyin: 'ma ma ming tian qu you ju ji xin ma', meaning: 'Mẹ ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '哥哥去邮局寄信吗？', pinyin: 'ge ge qu you ju ji xin ma', meaning: 'Anh trai đi bưu điện gửi thư phải không?' },
  { hanzi: '哥哥明天去邮局寄信。', pinyin: 'ge ge ming tian qu you ju ji xin', meaning: 'Anh trai ngày mai đi bưu điện gửi thư.' },
  { hanzi: '哥哥明天去邮局寄信吗？', pinyin: 'ge ge ming tian qu you ju ji xin ma', meaning: 'Anh trai ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '弟弟去邮局寄信吗？', pinyin: 'di di qu you ju ji xin ma', meaning: 'Em trai đi bưu điện gửi thư phải không?' },
  { hanzi: '弟弟明天去邮局寄信。', pinyin: 'di di ming tian qu you ju ji xin', meaning: 'Em trai ngày mai đi bưu điện gửi thư.' },
  { hanzi: '弟弟明天去邮局寄信吗？', pinyin: 'di di ming tian qu you ju ji xin ma', meaning: 'Em trai ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '妹妹去邮局寄信吗？', pinyin: 'mei mei qu you ju ji xin ma', meaning: 'Em gái đi bưu điện gửi thư phải không?' },
  { hanzi: '妹妹明天去邮局寄信。', pinyin: 'mei mei ming tian qu you ju ji xin', meaning: 'Em gái ngày mai đi bưu điện gửi thư.' },
  { hanzi: '妹妹明天去邮局寄信吗？', pinyin: 'mei mei ming tian qu you ju ji xin ma', meaning: 'Em gái ngày mai đi bưu điện gửi thư phải không?' },
  { hanzi: '我也学汉语。', pinyin: 'wo ye xue han yu', meaning: 'Tôi cũng học tiếng Hán.' },
  { hanzi: '我学汉语吗？', pinyin: 'wo xue han yu ma', meaning: 'Tôi học tiếng Hán phải không?' },
  { hanzi: '我也学英语。', pinyin: 'wo ye xue ying yu', meaning: 'Tôi cũng học tiếng Anh.' },
  { hanzi: '我学英语吗？', pinyin: 'wo xue ying yu ma', meaning: 'Tôi học tiếng Anh phải không?' },
  { hanzi: '你也学汉语。', pinyin: 'ni ye xue han yu', meaning: 'Bạn cũng học tiếng Hán.' },
  { hanzi: '你学汉语吗？', pinyin: 'ni xue han yu ma', meaning: 'Bạn học tiếng Hán phải không?' },
  { hanzi: '你也学英语。', pinyin: 'ni ye xue ying yu', meaning: 'Bạn cũng học tiếng Anh.' },
  { hanzi: '你学英语吗？', pinyin: 'ni xue ying yu ma', meaning: 'Bạn học tiếng Anh phải không?' },
  { hanzi: '他也学汉语。', pinyin: 'ta ye xue han yu', meaning: 'Anh ấy cũng học tiếng Hán.' },
  { hanzi: '他学汉语吗？', pinyin: 'ta xue han yu ma', meaning: 'Anh ấy học tiếng Hán phải không?' },
  { hanzi: '他也学英语。', pinyin: 'ta ye xue ying yu', meaning: 'Anh ấy cũng học tiếng Anh.' },
  { hanzi: '他学英语吗？', pinyin: 'ta xue ying yu ma', meaning: 'Anh ấy học tiếng Anh phải không?' },
  { hanzi: '她也学汉语。', pinyin: 'ta ye xue han yu', meaning: 'Cô ấy cũng học tiếng Hán.' },
  { hanzi: '她学汉语吗？', pinyin: 'ta xue han yu ma', meaning: 'Cô ấy học tiếng Hán phải không?' },
  { hanzi: '她也学英语。', pinyin: 'ta ye xue ying yu', meaning: 'Cô ấy cũng học tiếng Anh.' },
  { hanzi: '她学英语吗？', pinyin: 'ta xue ying yu ma', meaning: 'Cô ấy học tiếng Anh phải không?' },
  { hanzi: '爸爸也学汉语。', pinyin: 'ba ba ye xue han yu', meaning: 'Bố cũng học tiếng Hán.' },
  { hanzi: '爸爸学汉语吗？', pinyin: 'ba ba xue han yu ma', meaning: 'Bố học tiếng Hán phải không?' },
  { hanzi: '爸爸也学英语。', pinyin: 'ba ba ye xue ying yu', meaning: 'Bố cũng học tiếng Anh.' },
  { hanzi: '爸爸学英语吗？', pinyin: 'ba ba xue ying yu ma', meaning: 'Bố học tiếng Anh phải không?' },
  { hanzi: '妈妈也学汉语。', pinyin: 'ma ma ye xue han yu', meaning: 'Mẹ cũng học tiếng Hán.' },
  { hanzi: '妈妈学汉语吗？', pinyin: 'ma ma xue han yu ma', meaning: 'Mẹ học tiếng Hán phải không?' },
  { hanzi: '妈妈也学英语。', pinyin: 'ma ma ye xue ying yu', meaning: 'Mẹ cũng học tiếng Anh.' },
  { hanzi: '妈妈学英语吗？', pinyin: 'ma ma xue ying yu ma', meaning: 'Mẹ học tiếng Anh phải không?' },
  { hanzi: '哥哥也学汉语。', pinyin: 'ge ge ye xue han yu', meaning: 'Anh trai cũng học tiếng Hán.' },
  { hanzi: '哥哥学汉语吗？', pinyin: 'ge ge xue han yu ma', meaning: 'Anh trai học tiếng Hán phải không?' },
  { hanzi: '哥哥也学英语。', pinyin: 'ge ge ye xue ying yu', meaning: 'Anh trai cũng học tiếng Anh.' },
  { hanzi: '哥哥学英语吗？', pinyin: 'ge ge xue ying yu ma', meaning: 'Anh trai học tiếng Anh phải không?' },
  { hanzi: '弟弟也学汉语。', pinyin: 'di di ye xue han yu', meaning: 'Em trai cũng học tiếng Hán.' },
  { hanzi: '弟弟学汉语吗？', pinyin: 'di di xue han yu ma', meaning: 'Em trai học tiếng Hán phải không?' },
  { hanzi: '弟弟也学英语。', pinyin: 'di di ye xue ying yu', meaning: 'Em trai cũng học tiếng Anh.' },
  { hanzi: '弟弟学英语吗？', pinyin: 'di di xue ying yu ma', meaning: 'Em trai học tiếng Anh phải không?' },
  { hanzi: '妹妹也学汉语。', pinyin: 'mei mei ye xue han yu', meaning: 'Em gái cũng học tiếng Hán.' },
  { hanzi: '妹妹学汉语吗？', pinyin: 'mei mei xue han yu ma', meaning: 'Em gái học tiếng Hán phải không?' },
  { hanzi: '妹妹也学英语。', pinyin: 'mei mei ye xue ying yu', meaning: 'Em gái cũng học tiếng Anh.' },
  { hanzi: '妹妹学英语吗？', pinyin: 'mei mei xue ying yu ma', meaning: 'Em gái học tiếng Anh phải không?' },
  { hanzi: '我们明天见吗？', pinyin: 'wo men ming tian jian ma', meaning: 'Chúng ta gặp nhau ngày mai phải không?' },
  { hanzi: '明天见吗？', pinyin: 'ming tian jian ma', meaning: 'Hẹn gặp ngày mai phải không?' }
];

const allSentences = [...easySentences, ...hardSentences];

const dataMeta = {
  vocabCount: vocabList.length,
  sentenceCount: allSentences.length,
};

  Object.assign(HB, {
    vocabList,
    easySentences,
    hardSentences,
    allSentences,
    dataMeta,
  });
})(window);
